services:
  market-app:
    container_name: market-app
    restart: on-failure
    build: .
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: r2dbc:postgresql://postgres:5432/ya
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
    networks:
      - market-net
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:16-alpine
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ya
    ports:
      - "5433:5432"
    networks:
      - market-net
    volumes:
      - postgres-data-new:/var/lib/posgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "postgres", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

volumes:
  postgres-data-new:
networks:
  market-net: